### ISSUE TITLE
Duration doesn't exceed 23:59

### ISSUE THREAD

**Issue by daniel-zullo-frequenz** [frequenz-floss/frequenz-client-dispatch-python#90]
### What happened?

**Setting duration to 23:59 works**
```sh
dispatch-cli --url grpc://fz-0004.frequenz.io:50052 --key "********" create 174 peak-shaving BATTERY 23:00 23:59
Using API URL: grpc://fz-0004.frequenz.io:50052
Dispatch(id=127,
         type='peak-shaving',
         start_time=datetime.datetime(2024, 9, 23, 21, 0, tzinfo=datetime.timezone.utc),
         duration=datetime.timedelta(seconds=6375),
         selector=[<ComponentCategory.BATTERY: 5>],
         active=True,
         dry_run=False,
         payload={},
         recurrence=RecurrenceRule(frequency=<Frequency.UNSPECIFIED: 0>,
                                   interval=0,
                                   end_criteria=None,
                                   byminutes=[],
                                   byhours=[],
                                   byweekdays=[],
                                   bymonthdays=[],
                                   bymonths=[]),
         create_time=datetime.datetime(2024, 9, 23, 20, 12, 45, 482752, tzinfo=datetime.timezone.utc),
         update_time=datetime.datetime(2024, 9, 23, 20, 12, 45, 482752, tzinfo=datetime.timezone.utc))
Dispatch created.
```

**Setting duration to 00:00 does NOT work**
```sh
dispatch-cli --url grpc://fz-0004.frequenz.io:50052 --key "********" create 174 peak-shaving BATTERY 23:00 00:00
Using API URL: grpc://fz-0004.frequenz.io:50052
Traceback (most recent call last):
  File "/home/daniz/projects/frequenz-client-dispatch-python/.venv/bin/dispatch-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/daniz/projects/frequenz-client-dispatch-python/src/frequenz/client/dispatch/__main__.py", line 469, in main
    asyncio.run(cli.main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/daniz/projects/frequenz-client-dispatch-python/.venv/lib/python3.12/site-packages/asyncclick/core.py", line 1120, in main
    rv = await self.invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniz/projects/frequenz-client-dispatch-python/.venv/lib/python3.12/site-packages/asyncclick/core.py", line 1739, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniz/projects/frequenz-client-dispatch-python/.venv/lib/python3.12/site-packages/asyncclick/core.py", line 1485, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniz/projects/frequenz-client-dispatch-python/.venv/lib/python3.12/site-packages/asyncclick/core.py", line 824, in invoke
    rv = await rv
         ^^^^^^^^
  File "/home/daniz/projects/frequenz-client-dispatch-python/src/frequenz/client/dispatch/__main__.py", line 273, in create
    dispatch = await ctx.obj["client"].create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniz/projects/frequenz-client-dispatch-python/src/frequenz/client/dispatch/_client.py", line 285, in create
    request.to_protobuf(), metadata=self._metadata
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniz/projects/frequenz-client-dispatch-python/src/frequenz/client/dispatch/_internal_types.py", line 118, in to_protobuf
    dispatch_data=DispatchData(
                  ^^^^^^^^^^^^^
ValueError: Value out of range: -79982
```

### What did you expect instead?

I'd expect to be able to set a 24 hours duration at least

### Affected version(s)

v0.6.0

### Affected part(s)

I don't know (part:❓)

**Comment by llucax** [comment]
I don´t  understand the report, you say you want a duration of 24 hours, but you are actually requesting a duration of 0. This should still be supported (and mean instantaneous, though, but that's a separate issue). Am I missing something?

Another separate issue is the error message is really bad :disappointed:

**Comment by Marenz** [comment]
```
> create 1 "FCR" BATTERY "5 seconds" 24h
Using API URL: grpc://127.0.0.1:50051
Dispatch(id=14311,
         type='FCR',
         start_time=datetime.datetime(2024, 9, 24, 8, 22, 2, tzinfo=datetime.timezone.utc),
         duration=datetime.timedelta(days=1),
         selector=[<ComponentCategory.BATTERY: 5>],
         active=True,
         dry_run=False,
         payload={},
         recurrence=RecurrenceRule(frequency=<Frequency.UNSPECIFIED: 0>,
                                   interval=0,
                                   end_criteria=None,
                                   byminutes=[],
                                   byhours=[],
                                   byweekdays=[],
                                   bymonthdays=[],
                                   bymonths=[]),
         create_time=datetime.datetime(2024, 9, 24, 8, 21, 57, 220894, tzinfo=datetime.timezone.utc),
         update_time=datetime.datetime(2024, 9, 24, 8, 21, 57, 220894, tzinfo=datetime.timezone.utc))
Dispatch created.
```

**Comment by daniel-zullo-frequenz** [comment]
> I don´t understand the report, you say you want a duration of 24 hours, but you are actually requesting a duration of 0

I meant I want to run something from 23:00 to 22:59, but I misunderstood the CLI. The duration needs a unit. Closing but this needs better docs
